apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  jenkins.conf: |-
    upstream jenkins {
        server 172.19.118.74:8888;
    }
    server {
        listen 80;
        server_name  jenkins.codeeper.com;
        client_max_body_size 60M;
        client_body_buffer_size 512k;
        location / {
            proxy_pass http://jenkins;
            proxy_redirect     default;
            proxy_set_header   Host             $host:$server_port;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
  testphp.conf: |-
    server {
        listen 80;
        server_name testphp.codeeper.com;
        index index.php;
        root /opt/www/test_php/;

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_index index.php;
            fastcgi_pass testphp-svc:9000;
        }
    }
