apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ing
  annotations:
    kubernetes.io/ingress.class: "nginx" 
spec:
  tls:
  - hosts:
    - codeeper.com
    secretName: blog-tls-secret
  rules:
  - host: test.codeeper.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 80
  - host: codeeper.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 80
