apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vhost-conf
data:
  blog.conf: |-
    server {
      listen      80;
      server_name www.codeeper.com codeeper.com;
      charset     utf-8;

      location / {
        root   /var/www/blog;
        index  index.html index.htm;
      }
    }
