apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vhost-conf
data:
  jenkins.conf: |-
    upstream jenkins {
        server 172.19.118.74:8888;
    }
    server {
        listen 80;
        server_name  jenkins.codeeper.com;
        client_max_body_size 60M;
        client_body_buffer_size 512k;
        location / {
            proxy_pass http://jenkins;
            proxy_redirect     default;
            proxy_set_header   Host             $host:$server_port;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
  blog.conf: |-
    server {
      listen      80;
      server_name www.codeeper.com codeeper.com;
      charset     utf-8;

      location / {
        root   /var/www/blog;
        index  index.html index.htm;
      }
    }
  brbt.conf: |-
    server {
      listen      80;
      server_name brbt.codeeper.com;
      charset     utf-8;

      location ~ ^/h5 {
        root /var/www/brbt_h5;
        index index.html;
        try_files $uri $uri/ /h5/index.html;
      }

      location ~ ^/master {
        root /var/www/brbt_master;
        index index.html;
        try_files $uri $uri/ /master/index.html;
      }

      location ~ ^/static {
        alias /var/www/brbt/static;
      }

      location ~ ^/uploads {
        alias /var/www/brbt/uploads;
      }
    }
